# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径#修改配置application.yml中的basename国际化文件，默认是i18n路径下messages文件
    basename: static/i18n/messages
server:
  port: 8888